// Code generated by "stringer -type StepOrd -trimprefix StepOrd"; DO NOT EDIT.

package infra

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StepOrdTmplt-0]
	_ = x[StepOrdInit-1]
	_ = x[StepOrdPlan-2]
	_ = x[StepOrdApply-3]
	_ = x[StepOrdAddons-4]
	_ = x[StepOrdTest-5]
	_ = x[StepOrdLast-6]
}

const _StepOrd_name = "TmpltInitPlanApplyAddonsTestLast"

var _StepOrd_index = [...]uint8{0, 5, 9, 13, 18, 24, 28, 32}

func (i StepOrd) String() string {
	if i < 0 || i >= StepOrd(len(_StepOrd_index)-1) {
		return "StepOrd(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StepOrd_name[_StepOrd_index[i]:_StepOrd_index[i+1]]
}
