// Code generated by "stringer -type StepType -trimprefix StepType"; DO NOT EDIT.

package step

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StepTypeInit-0]
	_ = x[StepTypePlan-1]
	_ = x[StepTypeApply-2]
	_ = x[StepTypePool-3]
	_ = x[StepTypeKubeconfig-4]
	_ = x[StepTypeAddons-5]
	_ = x[StepTypeTest-6]
	_ = x[StepTypeLast-7]
}

const _StepType_name = "InitPlanApplyPoolKubeconfigAddonsTestLast"

var _StepType_index = [...]uint8{0, 4, 8, 13, 17, 27, 33, 37, 41}

func (i StepType) String() string {
	if i < 0 || i >= StepType(len(_StepType_index)-1) {
		return "StepType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StepType_name[_StepType_index[i]:_StepType_index[i+1]]
}
