// Code generated by "stringer -type Type -trimprefix Type"; DO NOT EDIT.

package step

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeInit-0]
	_ = x[TypePlan-1]
	_ = x[TypeApply-2]
	_ = x[TypePool-3]
	_ = x[TypeKubeconfig-4]
	_ = x[TypeAddons-5]
	_ = x[TypeTest-6]
	_ = x[TypeLast-7]
}

const _StepType_name = "InitPlanApplyPoolKubeconfigAddonsTestLast"

var _StepType_index = [...]uint8{0, 4, 8, 13, 17, 27, 33, 37, 41}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_StepType_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StepType_name[_StepType_index[i]:_StepType_index[i+1]]
}
